import { isProductionBuild } from "../config/env.js";

const developmentCopy = {
  productName: "Clinical Demo Workstation",
  gatewayUnavailable: "Demo Gateway 暂不可用。确认 Gateway 已在本机启动后刷新此页面。",
  scenarioLabel: "DEMO SCENARIOS",
  scenarioInstruction: "选择案例开始对话",
  scenarioAriaLabel: "演示案例",
  simpleScenario: "高血压复诊",
  complexScenario: "复杂病例",
  failureScenario: "故障演示",
  currentScenario: "当前案例",
  welcomeKicker: "SYNTHETIC CASE",
  welcomeTitle: "从患者上下文开始",
  welcomeDescription: "合成患者记忆与外部医学证据分别展示。回答只用于演示界面流程。",
  assistantLabel: "Huiyi · 合成演示回答",
  patientLoading: "正在载入合成患者…",
  patientEmptyTitle: "合成患者资料暂不可用。",
  patientEmptyHint: "请确认演示 Gateway 已启动后重试。",
  patientTag: "Synthetic demo patient",
  patientDataNote: "所有姓名、病程与内容均为合成演示数据。",
  composerPlaceholder: "描述本次复诊问题…",
  composerPrivacyHint: "合成演示 · 请勿输入真实患者信息",
  disclaimer: "本系统输出不构成诊断或治疗建议，需由医疗专业人员结合完整病史判断。",
  productionDecisionDisclaimer: "",
  activityCaption: "仅显示结构化执行元数据",
  activityEmpty: "发送问题后，执行活动会显示在这里。",
  presentationLabel: "PRESENTATION CASES",
  presentationTitle: "演示案例",
  singleTurnScenario: "单轮上下文与证据",
  specialistScenario: "DSH 临床协作",
  simulatedSpecialistScenario: "simulated multi-specialist flow",
  recoveryScenario: "故障与恢复",
  recoveryDescription: "fixture 错误状态测试",
  footerRuntimeSuffix: "合成病例",
  fixtureFooter: "CPU-only fixture · 合成数据 · 本地运行",
  fixtureEvidenceLabel: "Demo evidence fixture",
  fixtureEvidenceDisclaimer: "这些条目是为界面验收编写的合成资料，不是已核实的医学证据或医疗建议。",
  evidenceDisclaimer: "检索片段来自本地医学语料，需结合原始出处和具体临床情境核验，不构成诊断或治疗建议。",
  modelUnavailable: "模型配置不可用",
  fixtureBackendLabel: "Local · fixture",
  serviceUnavailable: "服务暂时不可用，请稍后重试。",
  retry: "重试",
  quickPromptVisit: "请根据本次复诊情况，帮我整理需要记录和向医生确认的问题。",
  quickPromptNextSteps: "请根据已有上下文，给我一个简洁的下一步沟通清单。",
} as const;

const productionCopy = {
  productName: "临床工作台",
  gatewayUnavailable: "服务连接暂不可用，请稍后重试或联系管理员。",
  scenarioLabel: "快捷工作流",
  scenarioInstruction: "从患者上下文开始",
  scenarioAriaLabel: "临床工作流",
  simpleScenario: "临床模板",
  complexScenario: "多学科协作",
  failureScenario: "",
  currentScenario: "当前病例",
  welcomeKicker: "当前病例",
  welcomeTitle: "从患者上下文开始",
  welcomeDescription: "请先加载患者上下文，再开始本次临床工作流。",
  assistantLabel: "慧宜助手",
  patientLoading: "正在加载患者上下文…",
  patientEmptyTitle: "尚未选择患者",
  patientEmptyHint: "请先加载患者上下文",
  patientTag: "",
  patientDataNote: "",
  composerPlaceholder: "描述本次复诊问题…",
  composerPrivacyHint: "请遵循机构隐私政策；输入可识别患者信息前，请确认已获得授权。",
  disclaimer: "本系统输出不构成诊断或治疗建议，需由医疗专业人员结合完整病史判断。",
  productionDecisionDisclaimer: "本系统仅用于辅助临床工作流，最终决策由执业医师负责。",
  activityCaption: "仅显示脱敏执行元数据",
  activityEmpty: "执行活动将在此显示。",
  presentationLabel: "临床工作流",
  presentationTitle: "快捷工作流",
  singleTurnScenario: "复诊沟通",
  specialistScenario: "多学科协作",
  simulatedSpecialistScenario: "多学科协作",
  recoveryScenario: "",
  recoveryDescription: "",
  footerRuntimeSuffix: "",
  fixtureFooter: "",
  fixtureEvidenceLabel: "医学证据来源",
  fixtureEvidenceDisclaimer: "",
  evidenceDisclaimer: "检索内容需由执业医师结合原始出处和完整病史核验，不构成诊断或治疗建议。",
  modelUnavailable: "模型信息暂不可用",
  fixtureBackendLabel: "服务配置不可用",
  serviceUnavailable: "服务暂时不可用，请稍后重试。",
  retry: "重试",
  quickPromptVisit: "请帮我整理本次复诊需要记录和向医生确认的问题。",
  quickPromptNextSteps: "请根据当前患者上下文整理下一步沟通清单。",
} as const;

export const clinicalCopy = isProductionBuild ? productionCopy : developmentCopy;
